import { ThemeProvider } from "@/components/theme"
import { CONSTANTS } from "@/constants"
import { ReactQueryProvider } from "@/react-query/provider"
import { ReduxProvider } from "@/redux/provider"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Plus_Jakarta_Sans } from "next/font/google"
import NextTopLoader from "nextjs-toploader"
import { Toaster } from "sonner"
import "./globals.css"

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] })

const applicationName = CONSTANTS.general.APPLICATION_NAME

export const metadata: Metadata = {
    title: {
        default: applicationName,
        template: `%s | ${applicationName}`,
    },
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const isMaintenance = CONSTANTS.general.MODE === "maintenance"

    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={jakarta.className}>
                    <NextTopLoader showSpinner={false} color="#7c3aed" />
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        disableTransitionOnChange
                    >
                        <ReduxProvider>
                            <ReactQueryProvider>
                                {isMaintenance ? <MaintenancePage /> : children}
                            </ReactQueryProvider>
                        </ReduxProvider>
                        <Toaster position="top-center" />
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}

const MaintenancePage = () => (
    <div className="container h-screen flex justify-center items-center">
        <div className="flex flex-col w-full items-center py-24">
            <h2 className="text-4xl font-bold text-center">
                {applicationName}
            </h2>
            <p className="mt-8 text-center">
                We are currently in maintenance mode. Please check back later.
            </p>
        </div>
    </div>
)
